### ISSUE TITLE
GOG.com no longer works (fixed for single-page operation)

### ISSUE THREAD

**Issue by lpmastor** [ssokolow/itad_importer#11]
GOG.com just updated the layout of it's My Account page and the script is no longer compatible.

See: http://www.gog.com/news/a_new_my_account and http://www.gog.com/forum/general/my_account_big_changes_on_the_horizon for details.

**Comment by ssokolow** [comment]
Yeah. GOG is one of my main sources of games and I'm already planning to fix it. It's just going to take a little while because I have:

1. Receive a reply from tfedor on the proper way to feed numeric GOG game IDs into the ITAD import API rather than URLs.
2. Make sufficient time to rework the script to support importing paginated content.

**Comment by ssokolow** [comment]
Oh, while I try to get an update written, the "On ITAD" entry it adds to the Share button on GOG's "Order Completed Successfully" page still works.

**Comment by Draky50110** [comment]
Subscribing, because I just discovered your awesome script... and GOG is my second games source ;)

**Comment by ssokolow** [comment]
:)

GOG's my first source (Humble's my second). I've just been stupidly busy these last two weeks so I haven't had much time to work on the script.

**Comment by Shi9k** [comment]
How is the progress on this issue?

**Comment by ssokolow** [comment]
Delayed due to exam-related backlogs. I'll start working on it either tomorrow or the day after.

**Comment by ssokolow** [comment]
Ok, I've finished merging the `humble-fix` branch so making major changes to the codebase won't cause merge conflicts and now I can dedicate my effort entirely to the GOG fix.

**Comment by ssokolow** [comment]
Ok, I've restored the button-insertion and scraping functionality, so you've got a "This Page" import button.

Now I just need to redesign the script so it can handle paginated input. (Which will also finally allow me to accept that contribution to support importing all bundles from Groupees with a single click.)

**Comment by Torin68** [comment]
Very nice having some GOG functionality, however the script does seem to miss a few items.
As an example: I own the complete Wing Commander series on GoG.com but not all of them appear on the import list. Notice the changes between the GoG store listing and my account 'game shelf' due to GoG 'unbundling': 'WC 1+2' splits to 'WC' and 'WC II', 'WC 5' splits to 'WC Prophesy' and 'WC Secret Ops'. Also, there are no links back to the store pages from these 'unbundled' entries. These games are completely missing from the ITAD import via the script. Any chance this can be rectified?

GoG store search for "wing comma"
WING COMMANDER ®: PRIVATEER ™
WING COMMANDER™ 1+2
WING COMMANDER™ 3 HEART OF THE TIGER™
WING COMMANDER™ 4: THE PRICE OF FREEDOM
WING COMMANDER™ 5: PROPHECY GOLD EDITION
WING COMMANDER™: ACADEMY
WING COMMANDER™: ARMADA

![wc_series_gog_account](https://cloud.githubusercontent.com/assets/11363623/8640335/c1ee456a-28c2-11e5-8634-28bb5c3666e7.jpg)
![wc_series_gog_import_itad](https://cloud.githubusercontent.com/assets/11363623/8640336/c1f11e3e-28c2-11e5-9e46-907ab1e39978.jpg)

**Comment by ssokolow** [comment]
Not a problem. I just removed the title-based fallback because I trusted ITAD's ability to recognize games by ID a little too much.

As soon as I get what I'm currently doing out of the way, it should only take me a couple of minutes to fix it.

**Comment by ssokolow** [comment]
There. Now the title fallback has been migrated over to GOG's new setup and, in my tests, all nine wing commander games show up in the ITAD listing.

**Comment by Draky50110** [comment]
Working for me :)

**Comment by flamanar** [comment]
Hi.  Thanks for the awesome script!  I do have a possible bug to report.  Similar to the one Torin68 had, but a different bundle.  QUEST FOR GLORY 1-5.  The script never picks up Quest for Glory 4.  It will pick up games 1,2,3, and 5...and also adds an entry "Quest for Glory 1-5".  Bizarre.  Just a heads-up.  thanks!

**Comment by ssokolow** [comment]
@flamanar Thanks for letting me know. I'll try to take a look tomorrow.

Would you mind filing a new bug for that so that, if we need to discuss further, we don't clutter up this one?

**Comment by flamanar** [comment]
Sure!  I'll have to do it tomorrow though, as I need to figure out how to file a new bug.  Yeah, I know...everybody's a newbie once :)  Thanks!

**Comment by ssokolow** [comment]
No worries. You just click the green New Issue button to the right of the "GOG.com no longer works (fixed for single-page operation)" title text at the top of the thread.

You'll get an entry form that's similar to what you're already using but also lets you provide a title.

Also, mention this issue so GitHub sets up a cross-reference. (Just say something like "issue #11" and GitHub will hyperlink the number and add a back-reference in this thread.)

**Comment by flamanar** [comment]
Thanks for the help with creating a new issue!  It's done, and I THINK I did it right.  Please let me know if I missed anything.  Thanks again!

**Comment by ssokolow** [comment]
Looks good and I've confirmed the issue.

I'll start diagnosing as soon as I can spare a moment and any further discussion will be on that issue.

**Comment by Shi9k** [comment]
Hi, the importer is not working for me when trying to collect the GOG pages. After the redirect, I always end up with the same result at https://isthereanydeal.com/outside/user/collection/3rdparty

![itad-gog-2015-09-10-16-13-42](https://cloud.githubusercontent.com/assets/7720037/9798452/519f6bd8-57d7-11e5-9517-a6fdfaa61bb5.png)

**Comment by ssokolow** [comment]
ITAD switched from HTTP to HTTPS and the redirect discards the information. I updated the script about a week ago but forgot to bump the version number.

I've now bumped the version number so, if you ask your browser to check for updates, it should notice the new version.

**Comment by ssokolow** [comment]
Note to self: Figure out how to stop people from posting on this issue rather than opening a new one.

**Comment by ssokolow** [comment]
There. Split out the relevant bit under a clearer name.
