### ISSUE TITLE
Humble : some games not checked at import ?

### ISSUE THREAD

**Issue by Draky50110** [ssokolow/itad_importer#12]
Hello

Just tried the script and if I export my Humble list, not all games are checked to import them on collection.
Some are, some not.

Why ?

Screenshot : [Imgur](http://i.imgur.com/DoYr8WDl.png)

**Comment by ssokolow** [comment]
I can't read it at that zoomed-out size. What does the small, low-contrast text on the right end of each line (before the store name) say?

**Comment by Draky50110** [comment]
Better uploaded resolution : https://lut.im/qOB98GpT/BjqohwTd

**Comment by ssokolow** [comment]
Ok, seeing that, I can say that my script is working perfectly well. The two types of unchecked entries in your screenshot are:

1. Games which say "in Collection", which means "Unchecked because it's already in your ITAD collection for this store from a previous import"
2. Non-games which say "unknown" which means "Unchecked because ITAD doesn't recognize this name as a game"

My script is working exactly as intended.

**Comment by Draky50110** [comment]
Thanks :)
