### ISSUE TITLE
HumbleBundle filter game title words

### ISSUE THREAD

**Issue by lkraider** [ssokolow/itad_importer#15]
Some games don't import on ITAD because HumbleBundle adds "Steam Key", "Origin Key" or just "Key" as suffix to their names.

Examples:
* Battlefield 3 ~~Origin Key~~
* Burnout Paradise: The Ultimate Box ~~Origin Key~~
* Burnout Paradise: The Ultimate Box ~~Steam Key~~
* Humble Frozenbyte Bundle ~~Desura Key~~
* Humble Frozenbyte Bundle ~~Steam Key~~
* The Sims 3 ~~Key~~

**Comment by ssokolow** [comment]
A similar issue popped up with Groupees import and the fix was integrated into ITAD rather than my script since it would significantly complicate my script while Tomáš (the ITAD guy) already has to maintain that sort of thing for ITAD's deduplication routines anyway.

Please report it at https://bitbucket.org/tfedor/isthereanydeal.com/issues instead.

**Comment by lkraider** [comment]
Will do, thanks.
